# Generated by Django 4.2.5 on 2023-10-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('modelo', models.ImageField(default=2000, upload_to='')),
                ('color', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('imagen', models.URLField(verbose_name='De imdb mismo')),
            ],
        ),
    ]
