# Generated by Django 4.2.5 on 2023-10-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
